### ISSUE TITLE
Installation of camera onto the drone

### ISSUE THREAD

**Issue by ZhiWei20011** [ctu-mrs/uvdar_gazebo_plugin#7]
Hi, I am fairly new to ROS and may I know the steps to install the camera onto the drone in order to detect the surrounding/terrain and objects? Which coding file should I access to?

**Comment by matemat13** [comment]
It depends on the camera you want to use. We're using Bluefox cameras with [this](https://github.com/ctu-mrs/bluefox2) driver.
