### ISSUE TITLE
Catkin build fails

### ISSUE THREAD

**Issue by lpmrz** [ctu-mrs/uvdar_gazebo_plugin#8]
Hello,

I cloned the package into the "~/mrs_workspace/src/uav_core/ros_packages/thirdparty" and tried to build it by "catkin build" but it gives the error below;

![Screenshot from 2021-08-24 16-52-51](https://user-images.githubusercontent.com/18270807/130629139-af9657c7-b5e1-43ef-89b1-cf86da1d6eb3.png)

**Comment by matemat13** [comment]
Do you have the `uvdar_core` package? It seems that you're missing a message from that package.

**Comment by lpmrz** [comment]
I re-cloned both `uvdar_core` and `uvdar_gazebo_plugin` and re-built them. Now they work, however this time drones do not spawn. Error is as below;

![Error](https://user-images.githubusercontent.com/18270807/130940021-0dfce580-abba-423b-a42c-ba730ee2e068.png)

**Comment by matemat13** [comment]
Aeems like you are using an outdated spawning method. Please see https://ctu-mrs.github.io/docs/simulation/drone_spawner.html.

**Comment by lpmrz** [comment]
Now they have spanned, but there is something wrong. There is an error in the control pane.

![Screenshot from 2021-08-30 17-02-37](https://user-images.githubusercontent.com/18270807/131351833-ea65609f-a5ec-4a7f-a00f-27b1dbf56fde.png)

![Screenshot from 2021-08-30 17-03-40](https://user-images.githubusercontent.com/18270807/131351879-aa9315d7-c026-4fc7-bb27-afbb893c6c10.png)

**Comment by matemat13** [comment]
Do as the message tells you - build the MpcTracker package. It will probably not be the only package that you forgot to build. I recommend going to the `uav_core` git repository, `git pull` there and then `catkin build` the whole workspace.

As a general rule - please do put at least some amount of work into trying to make the thing work before opening an issue :) The system is documented here on GitHub and over at [ctu-mrs.github.io](ctu-mrs.github.io), and the documentation should be plenty sufficient to deal with all common errors.

**Comment by ViktorWalter** [comment]
Sorry, the Readme file is out of date. The `beacon_test.sh` is deprecated. Currently, we use `new_signaling.sh`. I'm gonna update the README.

**Comment by ViktorWalter** [comment]
Ok, I have updated the `uvdar_core` Readme. Please, test it with the `new_signaling.sh` script.

**Comment by lpmrz** [comment]
Sorry for not reviewing the documentation better, and thank you for still helping me. I will put in more effort before opening an issue next time. On the other hand, I am still having errors despite I did everything you said and tried `new_signaling.sh`. I may have broken some things while I was experimenting before. Therefore I think it is best if I reinstall everything from scratch. 

Currently when I run `new_signaling.sh` drones do not spawn initially and the error is; 

`ERROR: Service [/mrs_drone_spawner/spawn] is not available.` 

So I launch `mrs_drone_spawner` in another tab and try again, this time the error for the first drone is; 

`message: "Cannot spawn vehicle. Reason: Param 'enable_dual_uv_cameras' not recognized!"`

The error for the rest of the drones is;

`message: "Cannot spawn vehicle. Reason: Param 'uvled_s_l' not recognized!"`

As I said previously, maybe it is better if I reinstall everything from the scratch. Thank you for trying to help me:)

**Comment by lpmrz** [comment]
> Ok, I have updated the `uvdar_core` Readme. Please, test it with the `new_signaling.sh` script.

I re-installed everything did `catkin clean` and `catkin build`. I test it with the `new signalling.sh`. I also cloned and built `mrs_serial` additionaly. Now drones spawn without a problem. However there are two problems I though I should mention. first one is, in the `uv_observer` pane;

![Screenshot from 2021-08-31 16-04-21](https://user-images.githubusercontent.com/18270807/131507612-4024a522-0267-4917-8148-db8cd6dee1aa.png)

and the other one is in the `sq_setter` pane

![Screenshot from 2021-08-31 16-06-10](https://user-images.githubusercontent.com/18270807/131507698-6b861d23-9ebe-4d57-a649-a9a936dc4bf8.png)

Does uvdar package depend on `mrs_serial`? Is there any way I could test uvdar without it? Thank you very much for sparing time and helping me.

**Comment by kielerrr** [comment]
> edit: Since my problem is solved, I can close the issue thank you again.

What was your solution?
